pool:
  name: Azure Pipelines

steps:
    - checkout: self
    - script: dir $(Build.SourcesDirectory)
    - task: UseDotNet@2
      inputs:
        packageType: 'sdk'
        version: '9.0.100'
        installationPath: '$(Agent.ToolsDirectory)/dotnet'
    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs:
        command: restore
        projects: '**/*.csproj'
        nugetConfigPath: 'nuget.config'
        feedsToUse: config

    - task: DotNetCoreCLI@2
      displayName: Publish
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--output $(build.artifactstagingdirectory)'
        zipAfterPublish: True
        projects: '**/*.csproj'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
      condition: succeededOrFailed()
